### ISSUE TITLE
instrumentation does not work on windows

### ISSUE THREAD

**Issue by motazreda** [attekett/NodeFuzz#3]
when run nodefuzz in windows 10 it run very nicely but after found a crash it uses instrumentation so it throws error.
the problem is it not reproduce the crash file either because it stopped in instrumentation step

so is there any way to disable instrumentation and just report me the crash testcases 

Thanks

**Comment by attekett** [comment]
The instrumentation module included in the source is for Linux AddressSanitizer build. Without AddressSanitizer that instrumentation module cannot detect crashes. To use nodefuzz on Windows you would need AddressSanitizer build that runs on Windows, or a Windows specific instrumentation module. 

It is possible to just modify the instrumentation file, by removing the stderr and stdout handlers and write the test case from browser.on('exit') handler, but with that approach you won't have duplicate detection and also timeouts are saved.

**Comment by motazreda** [comment]
could you please just tell me example of using browser.on instead of stderr, just to understand it correctly,
and i will try to make instrumentation, because all i need is the testcase file that made the crash, so i dont need anything else except the testcase file so i think it will be more simpler

**Comment by attekett** [comment]
Sorry for the late response. I missed the notification about your followup.

I decided to release a bundle of different instrumentation examples. I'll try to collect all the dependencies together during this weekend.

**Comment by attekett** [comment]
Released experimental Windows instrumentations: 85de3255b1718f7f35db5e8d126d5459bfc30ff1
